-- MySQL Script generated by MySQL Workbench
-- Sat Nov  1 14:58:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema conversations_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema conversations_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `conversations_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `conversations_db`;

-- -----------------------------------------------------
-- Table `conversations_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conversations_db`.`categories`
(
    `id_cat`          INT          NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор категории',
    `name_cat`        VARCHAR(255)  NOT NULL COMMENT 'Имя категории',
    `description_cat` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Описание категории',
    `created_at`      TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT 'Дата создания',
    PRIMARY KEY (`id_cat`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `conversations_db`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conversations_db`.`tags`
(
    `id_tag`   INT         NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор тега',
    `name_tag` VARCHAR(255) NOT NULL COMMENT 'Имя тега, допустим История")',
    PRIMARY KEY (`id_tag`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `conversations_db`.`lessons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conversations_db`.`lessons`
(
    `id_les`            INT          NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор лекции',
    `title_les`         VARCHAR(45)  NOT NULL COMMENT 'Заголовок лекции',
    `description_les`   VARCHAR(255) NULL     DEFAULT NULL COMMENT 'Описание лекции',
    `date_les`          DATE         NOT NULL COMMENT 'Назначенная дата лекции',
    `grade_level_les`   VARCHAR(45)  NOT NULL COMMENT 'Уровень класса (1-9)',
    `created_at`        DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `tags_id_tag`       INT          NOT NULL,
    `categories_id_cat` INT          NOT NULL,
    PRIMARY KEY (`id_les`),
    INDEX `fk_lessons_tags_idx` (`tags_id_tag` ASC) VISIBLE,
    INDEX `fk_lessons_categories1_idx` (`categories_id_cat` ASC) VISIBLE,
    CONSTRAINT `fk_lessons_tags`
        FOREIGN KEY (`tags_id_tag`)
            REFERENCES `conversations_db`.`tags` (`id_tag`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_lessons_categories1`
        FOREIGN KEY (`categories_id_cat`)
            REFERENCES `conversations_db`.`categories` (`id_cat`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
